-- MySQL Script generated by MySQL Workbench
-- Mon Sep  8 13:34:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alertly
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alertly
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alertly` DEFAULT CHARACTER SET utf8 ;
USE `alertly` ;

-- -----------------------------------------------------
-- Table `alertly`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`account` (
  `account_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `nickname` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `role` ENUM('citizen', 'admin') NULL DEFAULT 'citizen',
  `phone_number` VARCHAR(10) NULL,
  `activation_code` CHAR(5) NULL,
  `status` ENUM('pending_activation', 'active', 'inactive', 'blocked') NULL DEFAULT 'pending_activation',
  `credibility` DECIMAL(3,1) NULL DEFAULT 5.0,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `is_private_profile` TINYINT(1) NULL DEFAULT 0,
  `score` INT UNSIGNED NULL DEFAULT 0,
  `is_premium` TINYINT UNSIGNED NULL DEFAULT 1,
  `premium_expired_date` TIMESTAMP NULL,
  `counter_total_incidents_created` INT UNSIGNED NULL DEFAULT 0,
  `counter_total_votes_made` INT UNSIGNED NULL DEFAULT 0,
  `counter_total_comments_made` INT NULL DEFAULT 0,
  `counter_total_locations` INT NULL DEFAULT 0,
  `counter_total_flags` INT NULL DEFAULT 0,
  `counter_total_medals` INT NULL DEFAULT 0,
  `birth_year` CHAR(4) NULL,
  `birth_month` CHAR(2) NULL,
  `birth_day` CHAR(2) NULL,
  `has_finished_tutorial` CHAR(2) NULL DEFAULT 0,
  `has_watch_new_incident_tutorial` CHAR(2) NULL DEFAULT 0,
  `thumbnail_url` VARCHAR(200) NULL DEFAULT 'https://api.alertly.ca/images/profile/profile.webp',
  `last_notifications_view` TIMESTAMP NULL,
  `counter_new_notifications` SMALLINT UNSIGNED NULL DEFAULT 1,
  `crime` SMALLINT UNSIGNED NULL DEFAULT 0,
  `traffic_accident` SMALLINT UNSIGNED NULL DEFAULT 0,
  `medical_emergency` SMALLINT UNSIGNED NULL DEFAULT 0,
  `fire_incident` SMALLINT UNSIGNED NULL DEFAULT 0,
  `vandalism` SMALLINT UNSIGNED NULL DEFAULT 0,
  `suspicious_activity` SMALLINT UNSIGNED NULL DEFAULT 0,
  `infrastructure_issues` SMALLINT UNSIGNED NULL DEFAULT 0,
  `extreme_weather` SMALLINT UNSIGNED NULL DEFAULT 0,
  `community_events` SMALLINT UNSIGNED NULL DEFAULT 0,
  `dangerous_wildlife_sighting` SMALLINT UNSIGNED NULL DEFAULT 0,
  `positive_actions` SMALLINT UNSIGNED NULL DEFAULT 0,
  `lost_pet` SMALLINT UNSIGNED NULL DEFAULT 0,
  `incident_as_update` SMALLINT UNSIGNED NULL DEFAULT 0,
  `can_update_email` SMALLINT NULL DEFAULT 1,
  `can_update_nickname` SMALLINT NULL DEFAULT 1,
  `can_update_fullname` SMALLINT NULL DEFAULT 1,
  `can_update_birthdate` SMALLINT NULL DEFAULT 1,
  `receive_notifications` SMALLINT UNSIGNED NULL DEFAULT 1,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`account_session_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`account_session_history` (
  `ash_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `ip` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ash_id`),
  INDEX `fk_account_session_history_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_session_history_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`incident_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`incident_categories` (
  `inca_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` TEXT(1000) NULL,
  `icon_uri` VARCHAR(255) NULL,
  `code` VARCHAR(45) NULL,
  `border_color` CHAR(7) NULL,
  `default_circle_range` INT UNSIGNED NULL,
  `max_circle_range` INT UNSIGNED NULL,
  PRIMARY KEY (`inca_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`incident_subcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`incident_subcategories` (
  `insu_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inca_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NULL,
  `description` TEXT(1000) NULL,
  `icon` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `counter_uses` INT UNSIGNED NULL DEFAULT 0,
  `default_duration_hours` INT NOT NULL DEFAULT 48,
  PRIMARY KEY (`insu_id`),
  INDEX `fk_incident_subcategories_incident_categories1_idx` (`inca_id` ASC) VISIBLE,
  CONSTRAINT `fk_incident_subcategories_incident_categories1`
    FOREIGN KEY (`inca_id`)
    REFERENCES `alertly`.`incident_categories` (`inca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`incident_clusters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`incident_clusters` (
  `incl_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `center_latitude` DECIMAL(9,6) NULL,
  `center_longitude` DECIMAL(9,6) NULL,
  `start_time` TIMESTAMP NULL,
  `end_time` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `insu_id` TINYINT UNSIGNED NOT NULL,
  `incident_count` INT UNSIGNED NULL DEFAULT 1,
  `is_active` CHAR(2) NULL DEFAULT '1',
  `media_type` ENUM('image', 'video') NULL,
  `event_type` VARCHAR(45) NULL,
  `description` TEXT(1000) NULL,
  `address` VARCHAR(255) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `postal_code` VARCHAR(12) NULL,
  `counter_total_comments` INT NULL DEFAULT 0,
  `counter_total_votes` INT NULL DEFAULT 1,
  `counter_total_views` INT NULL DEFAULT 1,
  `counter_total_flags` INT NULL DEFAULT 0,
  `subcategory_name` VARCHAR(45) NULL,
  `counter_total_votes_true` INT NULL DEFAULT 1,
  `counter_total_votes_false` INT NULL DEFAULT 0,
  `media_url` VARCHAR(255) NULL,
  `subcategory_code` VARCHAR(100) NULL,
  `category_code` VARCHAR(100) NULL,
  `credibility` DECIMAL(3,1) NULL DEFAULT 5.0,
  `score_true` DECIMAL(10,2) NULL DEFAULT 0,
  `score_false` DECIMAL(10,2) NULL DEFAULT 0,
  `account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`incl_id`),
  INDEX `fk_incident_clusters_incident_subcategories1_idx` (`insu_id` ASC) VISIBLE,
  INDEX `fk_incident_clusters_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_incident_clusters_incident_subcategories1`
    FOREIGN KEY (`insu_id`)
    REFERENCES `alertly`.`incident_subcategories` (`insu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incident_clusters_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`incident_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`incident_reports` (
  `inre_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `incl_id` INT UNSIGNED NOT NULL,
  `insu_id` TINYINT UNSIGNED NOT NULL,
  `event_type` VARCHAR(40) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `description` TEXT(1000) NULL,
  `address` VARCHAR(255) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(25) NULL,
  `postal_code` VARCHAR(8) NULL,
  `latitude` DECIMAL(9,6) NULL,
  `longitude` DECIMAL(9,6) NULL,
  `status` ENUM('pending', 'verified', 'resolved', 'rejected') NULL,
  `counter_total_comments` INT UNSIGNED NULL DEFAULT 0,
  `counter_total_votes` INT UNSIGNED NULL DEFAULT 0,
  `counter_total_views` INT UNSIGNED NULL DEFAULT 0,
  `counter_total_flags` INT NULL DEFAULT 0,
  `is_anonymous` CHAR(2) NULL DEFAULT 0,
  `subcategory_name` VARCHAR(45) NULL,
  `counter_total_votes_true` INT NULL DEFAULT 0,
  `counter_total_votes_fake` INT NULL DEFAULT 0,
  `media_url` VARCHAR(200) NULL,
  `media_type` VARCHAR(20) NULL,
  `is_active` CHAR(2) NULL DEFAULT '1',
  `category_code` VARCHAR(100) NULL,
  `subcategory_code` VARCHAR(100) NULL,
  `vote` TINYINT UNSIGNED NULL DEFAULT 1,
  `credibility` DECIMAL(3,1) NULL DEFAULT 5.0,
  PRIMARY KEY (`inre_id`),
  INDEX `fk_incident_reports_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_incident_reports_incident_clusters1_idx` (`incl_id` ASC) VISIBLE,
  INDEX `fk_incident_reports_incident_subcategories1_idx` (`insu_id` ASC) VISIBLE,
  CONSTRAINT `fk_incident_reports_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incident_reports_incident_clusters1`
    FOREIGN KEY (`incl_id`)
    REFERENCES `alertly`.`incident_clusters` (`incl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incident_reports_incident_subcategories1`
    FOREIGN KEY (`insu_id`)
    REFERENCES `alertly`.`incident_subcategories` (`insu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`incident_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`incident_comments` (
  `inco_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `comment` TEXT(500) NULL,
  `created_at` TIMESTAMP NULL,
  `counter_flags` INT NULL DEFAULT 0,
  `incl_id` INT UNSIGNED NOT NULL,
  `comment_status` CHAR(2) NULL DEFAULT '1',
  PRIMARY KEY (`inco_id`),
  INDEX `fk_incident_comments_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_incident_comments_incident_clusters1_idx` (`incl_id` ASC) VISIBLE,
  CONSTRAINT `fk_incident_comments_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incident_comments_incident_clusters1`
    FOREIGN KEY (`incl_id`)
    REFERENCES `alertly`.`incident_clusters` (`incl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`incident_votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`incident_votes` (
  `invo_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `inre_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `vote` TINYINT NULL,
  PRIMARY KEY (`invo_id`),
  INDEX `fk_incident_votes_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_incident_votes_incident_reports1_idx` (`inre_id` ASC) VISIBLE,
  CONSTRAINT `fk_incident_votes_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incident_votes_incident_reports1`
    FOREIGN KEY (`inre_id`)
    REFERENCES `alertly`.`incident_reports` (`inre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`incident_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`incident_logs` (
  `inlo_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inre_id` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `event_type` ENUM('status_change', 'update', 'moderator_action') NULL,
  `message` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`inlo_id`),
  INDEX `fk_incident_logs_incident_reports1_idx` (`inre_id` ASC) VISIBLE,
  INDEX `fk_incident_logs_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_incident_logs_incident_reports1`
    FOREIGN KEY (`inre_id`)
    REFERENCES `alertly`.`incident_reports` (`inre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incident_logs_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`account_favorite_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`account_favorite_locations` (
  `afl_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NULL,
  `latitude` DECIMAL(9,6) NULL,
  `longitude` DECIMAL(9,6) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(25) NULL,
  `postal_code` VARCHAR(8) NULL,
  `status` TINYINT UNSIGNED NULL DEFAULT 1,
  `crime` TINYINT UNSIGNED NULL DEFAULT 1,
  `traffic_accident` TINYINT UNSIGNED NULL DEFAULT 1,
  `medical_emergency` TINYINT UNSIGNED NULL DEFAULT 1,
  `fire_incident` TINYINT UNSIGNED NULL DEFAULT 1,
  `vandalism` TINYINT UNSIGNED NULL DEFAULT 1,
  `suspicious_activity` TINYINT UNSIGNED NULL DEFAULT 1,
  `infrastructure_issues` TINYINT UNSIGNED NULL DEFAULT 1,
  `extreme_weather` TINYINT UNSIGNED NULL DEFAULT 1,
  `community_events` TINYINT UNSIGNED NULL DEFAULT 1,
  `dangerous_wildlife_sighting` TINYINT UNSIGNED NULL DEFAULT 1,
  `positive_actions` TINYINT UNSIGNED NULL DEFAULT 1,
  `lost_pet` TINYINT UNSIGNED NULL DEFAULT 1,
  `radius` SMALLINT UNSIGNED NULL DEFAULT 3000,
  PRIMARY KEY (`afl_id`),
  INDEX `fk_account_locations_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_locations_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`notifications` (
  `noti_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_account_id` INT UNSIGNED NULL,
  `title` VARCHAR(45) NULL,
  `message` TEXT NULL,
  `type` ENUM('welcome_to_app', 'new_comment', 'new_cluster', 'new_incident_cluster', 'earn_citizen_score', 'membership_expiration_10_days', 'membership_expiration_1_day', 'welcome_to_membership', 'password_reset', 'new_friend_request', 'user_mentioned', 'badge_earned', 'app_update', 'promotion', 'system_maintenance', 'inactivity_reminder', 'incident_result_win', 'incident_result_loss') NULL,
  `link` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `sent_at` TIMESTAMP NULL,
  `must_send_as_notification_push` TINYINT(1) UNSIGNED NULL DEFAULT 1,
  `must_send_as_notification` TINYINT(1) UNSIGNED NULL DEFAULT 1,
  `must_be_processed` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  `error_message` TEXT NULL,
  `retry_count` MEDIUMINT UNSIGNED NULL DEFAULT 0,
  `reference_id` INT UNSIGNED NULL,
  PRIMARY KEY (`noti_id`),
  INDEX `fk_account_notifications_account1_idx` (`owner_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_notifications_account1`
    FOREIGN KEY (`owner_account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`incident_flags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`incident_flags` (
  `infl_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inre_id` INT UNSIGNED NOT NULL,
  `reason` TEXT(2000) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`infl_id`),
  INDEX `fk_reports_incident_reports1_idx` (`inre_id` ASC) VISIBLE,
  INDEX `fk_incident_flags_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_reports_incident_reports1`
    FOREIGN KEY (`inre_id`)
    REFERENCES `alertly`.`incident_reports` (`inre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incident_flags_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`account_premium_payment_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`account_premium_payment_history` (
  `apph_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `type_plan` ENUM('free', '1 month', '6 months', '12 months') NULL DEFAULT 'free',
  `description` TEXT(1000) NULL,
  PRIMARY KEY (`apph_id`),
  INDEX `fk_account_premium_payment_history_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_premium_payment_history_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`account_achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`account_achievements` (
  `acac_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `show_in_modal` TINYINT UNSIGNED NULL DEFAULT 1,
  `type` VARCHAR(45) NULL,
  `text_to_show` VARCHAR(255) NULL,
  `icon_url` VARCHAR(255) NULL,
  `badge_threshold` INT NULL,
  PRIMARY KEY (`acac_id`),
  INDEX `fk_account_achievements_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_show` (`show_in_modal` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_account_achievements_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`account_cluster_saved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`account_cluster_saved` (
  `acs_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `incl_id` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`acs_id`),
  INDEX `fk_account_cluster_saved_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_account_cluster_saved_incident_clusters1_idx` (`incl_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_cluster_saved_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_cluster_saved_incident_clusters1`
    FOREIGN KEY (`incl_id`)
    REFERENCES `alertly`.`incident_clusters` (`incl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`notification_deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`notification_deliveries` (
  `node_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL,
  `is_read` TINYINT(2) UNSIGNED NULL DEFAULT 0,
  `to_account_id` INT UNSIGNED NOT NULL,
  `noti_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NULL,
  `message` TEXT(1000) NULL,
  PRIMARY KEY (`node_id`),
  INDEX `fk_notifications_deliveries_account1_idx` (`to_account_id` ASC) VISIBLE,
  INDEX `fk_notifications_deliveries_account_notifications1_idx` (`noti_id` ASC) VISIBLE,
  CONSTRAINT `fk_notifications_deliveries_account1`
    FOREIGN KEY (`to_account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notifications_deliveries_account_notifications1`
    FOREIGN KEY (`noti_id`)
    REFERENCES `alertly`.`notifications` (`noti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`account_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`account_reports` (
  `acre_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id_whos_reporting` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `message` VARCHAR(200) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`acre_id`),
  INDEX `fk_account_reports_account1_idx` (`account_id_whos_reporting` ASC) VISIBLE,
  INDEX `fk_account_reports_account2_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_reports_account1`
    FOREIGN KEY (`account_id_whos_reporting`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_reports_account2`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`account_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`account_history` (
  `his_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `incl_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`his_id`),
  INDEX `fk_account_history_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_account_history_incident_clusters1_idx` (`incl_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_history_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_history_incident_clusters1`
    FOREIGN KEY (`incl_id`)
    REFERENCES `alertly`.`incident_clusters` (`incl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`device_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`device_tokens` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `device_token` VARCHAR(255) NULL,
  `platform` ENUM('ios') NULL DEFAULT 'ios',
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_device_tokens_account1_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `device_token_UNIQUE` (`device_token` ASC) VISIBLE,
  CONSTRAINT `fk_device_tokens_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertly`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertly`.`feedback` (
  `fb_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `subject` VARCHAR(100) NULL,
  `description` TEXT(2000) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`fb_id`),
  INDEX `fk_feedback_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_feedback_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alertly`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `alertly`.`incident_categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `alertly`;
-- End of schema
